@baseUrl = http://localhost:3000/api/characters

### GET
GET {{baseUrl}}
Accept: application/json

### POST
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Muminek",
  "description": "Główny bohater, bardzo odważny.",
  "species": "Muminek",
  "isHibernating": true,
  "bestFriend": null
}

### PUT
PUT {{baseUrl}}/69d78e5ea1edf91f300d691d
Content-Type: application/json

{
  "name": "Muminek UPDATED",
  "description": "Zmieniony opis",
  "species": "Muminek",
  "isHibernating": false,
  "bestFriend": null
}

### DELETE
DELETE {{baseUrl}}/69d78e5ea1edf91f300d691d
Accept: application/json